spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: measurements
  application:
    name: measurements-service
server:
  port: '8080'
eureka:
  client:
    service-url:
      defaultZone: 'http://eureka:password@discovery-server:8761/eureka'
