spring:
  data:
    mongodb:
      uri: mongodb+srv://michal:UQruBVa80GwpxItm@cluster0.2wlc9t1.mongodb.net/devices?retryWrites=true&w=majority
      database: devices
  application:
    name: sensorsdata-service
server:
  port: '0'
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
