spring:
  datasource:
    url: jdbc:mysql://mysql.agh.edu.pl:3307/device-service
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: device-service
eureka:
  client:
    service-url:
      defaultZone: 'http://eureka:password@discovery-server:8761/eureka'
server:
  port: '8080'
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# Resilence4j properties
resilience4j:
  circuitbreaker:
    instances:
      measurements:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
